version: '3.8'

services:
  configmaster_server:
    build:
      context: .
      dockerfile: ConfigMaster.Server/Dockerfile
    ports:
      - "8080:8080" # Host portu:Container portu
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=postgres;Username=postgres;Password=postgres123
    networks:
      - configmaster_network

  configmaster_client:
    build:
      context: ./ConfigMaster.Client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - configmaster_server
    networks:
      - configmaster_network

networks:
  configmaster_network:
    driver: bridge
