version: '3.9'

services:
  backend:
    build:
      context: ./ConfigMaster.Server
    ports:
      - "5000:80"
    networks:
      - confignet

  frontend:
    build:
      context: ./configmaster.client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend
    networks:
      - confignet

networks:
  confignet:
    driver: bridge
